version: '3.8'

services:
  web:
    build: .
    ports:
      - "2233:3000"
    volumes:
      - 'case-report-data:/app/.data'
    environment:
      NUXT_AI_API_BASE_URL: ${NUXT_AI_API_BASE_URL}
      NUXT_AI_API_KEY: ${NUXT_AI_API_KEY}
      NUXT_AI_MODEL: ${NUXT_AI_MODEL}
    restart: always

volumes:
  case-report-data:
    driver: local
